---
- hosts: docker_host

  tasks:
  - name: pull code
    shell: git pull origin master && git submodule update
    args:
      chdir: "{{ project_root }}"

  - name: assemble war for paper-api
    shell: ./gradlew war
    args:
      chdir: "{{ project_root }}paper-api/"
    notify:
    - restart paper-api container

  - name: migrate mysql
    shell: ./gradlew flywaymigrate
    args:
      chdir: "{{ project_root }}paper-api/"

  - name: install dependencies for web-api
    shell: docker exec -d assembly_web-api_1 sh -c "cd /var/app; npm i -g yarn; yarn"
    notify:
    - restart web-api container

  - name: package the web
    shell: yarn && npm run webpack
    args:
      chdir: "{{ project_root }}web/"

  - name: package the admin-web
    shell: yarn && npm run webpack
    args:
      chdir: "{{ project_root }}teacher-admin-web/"

  - name: restore jenkins configration
    shell: docker exec -d assembly_jenkins-dind_1 sh -c " rm -rf /var/jenkins_home/jobs/{{ item.name }}; mkdir /var/jenkins_home/jobs/{{ item.name }}; "
          && docker cp "{{ project_root }}assembly/jenkins/{{ item.name }}/config.xml" "assembly_jenkins-dind_1:/var/jenkins_home/jobs/{{ item.name }}"
    with_items:
      - { name: ADD_HOMEWORK }
      - { name: ADD_IMAGE }
      - { name: HOMEWORK_SCORING }

  - name: restore jenkins plugins
    shell: docker cp {{ item }} "assembly_jenkins-dind_1:/var/jenkins_home/plugins/"
    with_fileglob:
      - "{{ project_root }}assembly/jenkins/plugins/*.hpi"
    notify:
      - restart jenkins container
    tags:
      - jenkins

  - name: create .ssh directory
    shell: cd "{{ project_root }}assembly/jenkins" && rm -rf .ssh && mkdir .ssh && echo ppp
    tags:
      - create

  - file:
      path: "~/.sshForSymbolicLink/{{ item.name }}"
      mode: "{{ item.mode }}"
    with_items:
      - { name: 'id_rsa', mode: 400 }
      - { name: 'id_rsa.pub', mode: 755 }
      - { name: 'known_hosts', mode: 666 }
    tags:
      - ssh

  handlers:
    - name: restart paper-api container
      shell: docker restart assembly_paper-api_1
    - name: restart web-api container
      shell: docker restart assembly_web-api_1
    - name: restart jenkins container
      shell: docker restart assembly_jenkins-dind_1